version: 2.1
<<<<<<< HEAD
orbs: 
  node: circleci/node@5.0.1
workflows:
  test:
    jobs:
      - node/test:
          test-results-for: jest
=======
orbs:
  node: circleci/node@3.0.0
workflows: 
node-test:
jobs:
   - node/test
>>>>>>> 730bcd8e85149356500855323136424b7e63664d
